portainer/agent

Gopkg.lock
Gopkg.toml
dev.sh
vendor/github.com/portainer/libhttp/error/error.go

chore(dep): update libhttp to version 1.1.0

---

README.md
agent.go
cmd/agent/main.go
os/options.go

feat(options): remove EDGE_POLL_FREQUENCY option

---

agent.go
cmd/agent/main.go
dev.sh
docker/docker.go

feat(docker): retrieve ClusterAddr via service name

---

http/server.go

Fixes #42 
Fixes #43 
Related to #85

feat(http): specify Read/Write timeouts for Server

---

http/proxy/cluster.go

Fix #42 
Fix #43 
Related to #86

feat(http): disable keep alive for resource aggregation client

---

dev.sh
http/handler/docker/docker_operation.go
http/proxy/agentproxy.go

feat(http): add more logging around failed proxy requests

---

http/proxy/cluster.go

feat(http): log failed resourceList request

---

dev.sh
http/proxy/cluster.go

Closes #79 
Adds a 3s timeout ping request before each resourceList operation.

feat(http): send short-lived ping request before resourceList request

---

README.md

Adds security info to the readme for the Agent

docs(project): add security info

---

filesystem/filesystem.go
http/handler/browse/browse_delete.go
http/handler/browse/browse_get.go
http/handler/browse/browse_list.go
http/handler/browse/browse_put.go
http/handler/browse/browse_rename.go

fix(http): prevent '..' in filename for browsePut operation

---

agent.go
cmd/agent/main.go
dev.sh
docker/docker.go
http/edge.go
http/handler/key/key_create.go
http/tunnel/tunnel.go

feat(tunnel): start polling only if leader

---

agent.go
http/client/portainer_client.go
internal/edge/stack.go

feat(edge-stacks): use edge stack name for deployed name

---

agent.go
cmd/agent/main.go
docker/docker.go
http/handler/docker/docker_operation.go
http/handler/docker/handler.go
http/handler/handler.go
http/handler/key/handler.go
http/handler/websocket/attach.go
http/handler/websocket/exec.go
http/handler/websocket/handler.go
http/proxy/agentproxy.go
http/server.go
internal/edge/edge.go
internal/edge/key.go
serf/cluster.go

refactor(agent): replace agentTags with a struct

---

internal/edge/poll.go

fix(poll): init refresh signal on restart

---

README.md
dev.sh
os/options.go

feat(options): deprecate CAP_HOST_MANAGEMENT env var

---

agent.go
filesystem/scheduler.go
http/client/portainer_client.go
internal/edge/edge.go
internal/edge/logs.go
internal/edge/poll.go

close #135 
related to https://github.com/portainer/portainer/pull/3840

feat(edge-jobs): collect logs

---

http/server.go

fix(crypto): use tls1.2 with recommended ciphers

---

http/server.go

feat(crypto): use tls1.2 with recommended ciphers

---

cmd/agent/main.go

related to https://github.com/portainer/agent/commit/98a6fb9f68938087aaeae2a13a0fddab87ceeda5

fix(main): set docker advertise addr

---

agent.go
cmd/agent/main.go
http/handler/handler.go
http/server.go
internal/edge/edge.go
internal/edge/poll.go

feat(agent): add auto agent platform detection

---

setup.sh

feat(build): upgrade docker version

---

build/windows/Dockerfile
setup.sh

Closes https://github.com/portainer/agent/issues/171

Feat171 introduce windows buildx

---

build/windows/Dockerfile

add back USER definition to windows Dockerfile that was removed for work on #171

fix(build): add back USER definition to Dockerfile

---

http/server.go

fix(image/build): Extend image pulling timeout

---

http/handler/dockerhub/dockerhub_status.go
http/handler/dockerhub/handler.go
http/handler/handler.go
http/handler/handlerv2.go

related to https://github.com/portainer/portainer/pull/4666

feat(docker): fetch docker pulls limits

---

dev-scripts/compile.sh

[CE-499]
[CE-499]: https://portainer.atlassian.net/browse/CE-499

chore(dev): compile dev script

---

http/server.go

fix: Bump server timeout to 30 minutes CE-158

---

agent.go
exec/kubernetes_deploy.go
http/handler/kubernetes/kubernetes_deploy.go
http/handler/websocket/pod.go
kubernetes/client.go

fix(stack): EE-1141 A standard user can escalate to cluster administrator privileges on Kubernetes

---

http/handler/dockerhub/dockerhub_status.go

Fixes [EE-1035](https://portainer.atlassian.net/browse/EE-1035)

fix(dockerhub): dockerhub ratelimit issues EE-1035

---

agent.go
cmd/agent/main.go
exec/docker_compose_stack.go
exec/docker_swarm_stack.go
exec/kubernetes_deploy.go
exec/utils.go
http/client/portainer_client.go
http/handler/handler.go
http/handler/kubernetes/handler.go
http/handler/kubernetes/kubernetes_deploy.go
http/server.go
internal/edge/edge.go
internal/edge/logs.go
internal/edge/poll.go
internal/edge/stack.go

needs to be merged with portainer PR (https://github.com/portainer/portainer-ee/pull/378)
blocked by #175

 feat(edge): support edge stacks for kubernetes

---

.github/workflows/label-conflcts.yaml

[DTD-66]
[DTD-66]: https://portainer.atlassian.net/browse/DTD-66

chore(github): add label conflicts workflow
